server:
  port: 8090


spring:
  profiles:
    include: main-service-common-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/image-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 48MB

file:
  upload-dir: C:\\Users\\user\\Desktop\\catalog-files

