server:
  port: 8090

spring:
  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 48MB

  datasource:
    url: jdbc:postgresql://postgres:5432/image-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  oauth2:
    resource:
      link: http://uaa-service:8089
      token-info-uri: ${security.oauth2.resource.link}/oauth/check_token
    client:
      client-id: akfa
      client-secret: akfaGroup1234

eureka:
  instance:
#    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

file:
  upload-dir: /home/storage

feign:

  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

  ribbon:
    news:
      name: news-service
      url: http://news-service:8090
    product:
      name: product-service
      url: http://product-service:8084
    catalog:
      name: catalog-service
      url: http://catalog-service:8083
