---
spring:
  profiles:
    active: main-service-common
  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  datasource:
    username: postgres
    password: root

security:
  oauth2:
    resource:
      link: http://uaa-service:8089
      token-info-uri: ${security.oauth2.resource.link}/oauth/check_token
    client:
      client-id: akfa
      client-secret: akfaGroup1234

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

---

spring:
  profiles:
    active: main-service-common-dev
  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021
  datasource:
    username: postgres
    password: root

security:
  oauth2:
    resource:
      link: http://localhost:8080/dev/auth-service
      token-info-uri: ${security.oauth2.resource.link}/oauth/check_token
    client:
      client-id: akfa
      client-secret: akfaGroup1234

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka