---
server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m

management:
  endpoints:
    web:
      exposure:
        include: '*'

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.erueka.default.svc.cluster.local:8761/eureka