server:
  port: 8083

security:
  oauth2:
    resource:
      link: http://localhost:8080/api/auth-service
      token-info-uri: ${security.oauth2.resource.link}/oauth/check_token
    client:
      client-id: akfa
      client-secret: akfaGroup1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka, http://localhost:8763/eureka, http://localhost:8764/eureka

spring:
  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalog-service
    username: postgres
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
