spring:
  config:
    activate:
      on-profile: docker

  eureka:
    client:
      serviceUrl:
        defaultZone: http://registry-service:8761/eureka/

  security:
    user:
      name: admin
      password: adminCatalog2021

server:
  port: 7700

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'