server:
  port: 8084

spring:
  profiles:
    include: main-service-common
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/product-service

refresh:
  scope:
    version: 0.0.2

feign:
  ribbon:
    catalog: catalog-service