server:
  port: 8084

security:
  oauth2:
    resource:
      link: http://uaa-service:8089
      token-info-uri: ${security.oauth2.resource.link}/oauth/check_token
    client:
      client-id: akfa
      client-secret: akfaGroup1234

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka


spring:

  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/product-service
    username: postgres
    password: root

refresh:
  scope:
    version: 0.0.2