server:
  port: 8089

spring:

  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:// 10.7.5.96:5432/uaa-service
    username: postgres
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always
