server:
  port: 9090

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

swagger:
  config:
    refreshrate: 5000

spring:
  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021
