server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

swagger:
  config:
    refreshrate: 5000

spring:
  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021
