server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka, http://localhost:8763/eureka, http://localhost:8764/eureka

swagger:
  config:
    refreshrate: 5000

spring:
  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021
