server:
  port: 9090

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka

swagger:
  config:
    refreshrate: 5000

spring:
  boot:
    admin:
      client:
        url:
          - http://admin-servoce:7700
        username: admin
        password: adminCatalog2021
