server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka, http://localhost:8763/eureka, http://localhost:8764/eureka

swagger:
  config:
    refreshrate: 5000
