server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021
  zipkin:
    baseUrl: http://tracing-server:9411
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service
                fallbackuri: forward:/uaaServiceFallBack

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalog-service
                fallbackuri: forward:/catalogServiceFallBack

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productServiceFallBack

        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: news-service
                fallbackuri: forward:/newsServiceFallBack

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/image-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: image-service
                fallbackuri: forward:/imageServiceFallBack

        - id: swagger-service
          uri: lb://swagger-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service
                fallbackuri: forward:/swaggerServiceFallBack

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream