server:
  port: 8080

spring:

  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  cloud:
    gateway:
      routes:

        - id: UAA-SERVICE-DOCKER
          uri: lb://UAA-SERVICE-DOCKER
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: UAA-SERVICE-DOCKER
                fallbackuri: forward:/uaaServiceFallBack

        - id: CATALOG-SERVICE-DOCKER
          uri: lb://CATALOG-SERVICE-DOCKER
          predicates:
            - Path=/api/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: CATALOG-SERVICE-DOCKER
                fallbackuri: forward:/catalogServiceFallBack

        - id: PRODUCT-SERVICE-DOCKER
          uri: lb://PRODUCT-SERVICE-DOCKER
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE-DOCKER
                fallbackuri: forward:/productServiceFallBack

        - id: SWAGGER-SERVICE-DOCKER
          uri: lb://SWAGGER-SERVICE-DOCKER
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: SWAGGER-SERVICE-DOCKER
                fallbackuri: forward:/categoryServiceFallBack


eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
