server:
  port: 8080

spring:

  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021

  cloud:
    gateway:
      loadbalancer:
        ribbon:
          enabled: false
      #      connect-timeout: 6000
#        response-timeout: 6s
      routes:

        - id: uaa-service-dev
          uri: lb://uaa-service-dev
          predicates:
            - Path=/dev/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service-dev
                fallbackuri: forward:/uaaServiceFallBack

        - id: catalog-service-dev
          uri: lb://catalog-service-dev
          predicates:
            - Path=/dev/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalog-service-dev
                fallbackuri: forward:/catalogServiceFallBack

        - id: product-service-dev
          uri: lb://product-service-dev
          predicates:
            - Path=/dev/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-service-dev
                fallbackuri: forward:/productServiceFallBack

        - id: news-service-dev
          uri: lb://news-service-dev
          predicates:
            - Path=/dev/news-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: news-service-dev
                fallbackuri: forward:/newsServiceFallBack

        - id: image-service-dev
          uri: lb://image-service-dev
          predicates:
            - Path=/dev/image-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: image-service-dev
                fallbackuri: forward:/imageServiceFallBack

        - id: swagger-service-dev
          uri: lb://swagger-service-dev
          predicates:
            - Path=/dev/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service-dev
                fallbackuri: forward:/swaggerServiceFallBack


eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
