server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service
                fallbackuri: forward:/uaaServiceFallBack

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalog-service
                fallbackuri: forward:/catalogServiceFallBack

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productServiceFallBack

        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: news-service
                fallbackuri: forward:/newsServiceFallBack

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/image-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: image-service
                fallbackuri: forward:/imageServiceFallBack

        - id: swagger-service
          uri: lb://swagger-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service
                fallbackuri: forward:/swaggerServiceFallBack
eureka:
  instance:
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
