server:
  port: 8080

spring:

  zipkin:
    baseUrl: http://localhost:9411

  boot:
    admin:
      client:
        url:
          - http://localhost:7700
        username: admin
        password: adminCatalog2021

  cloud:
    gateway:
      routes:

        - id: uaa-service-dev
          uri: lb://uaa-service-dev
          predicates:
            - Path=/dev/auth-service/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service-dev
                fallbackuri: forward:/uaaServiceFallBack

        - id: catalog-service-dev
          uri: lb://catalog-service-dev
          predicates:
            - Path=/dev/catalog-service/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalog-service-dev
                fallbackuri: forward:/catalogServiceFallBack

        - id: product-service-dev
          uri: lb://product-service-dev
          predicates:
            - Path=/dev/product-service/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-service-dev
                fallbackuri: forward:/productServiceFallBack

        - id: news-service-dev
          uri: lb://news-service-dev
          predicates:
            - Path=/dev/news-service/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: news-service-dev
                fallbackuri: forward:/newsServiceFallBack

        - id: image-service-dev
          uri: lb://image-service-dev
          predicates:
            - Path=/dev/image-service/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: image-service-dev
                fallbackuri: forward:/imageServiceFallBack


        - id: swagger-service-dev
          uri: lb://swagger-service-dev
          predicates:
            - Path=/dev/**
          filters:
            - Hystrix=fallbackcmd
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service-dev
                fallbackuri: forward:/swaggerServiceFallBack

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

testme: hello