server:
  port: 8080

spring:

  boot:
    admin:
      client:
        url:
          - http://admin-service:7700
        username: admin
        password: adminCatalog2021

  cloud:
    gateway:
      loadbalancer:
        ribbon:
          enabled: true
      routes:

        - id: uaa-service-docker
          uri: lb://uaa-service-docker
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service-docker
                fallbackuri: forward:/uaaServiceFallBack

        - id: catalog-service-docker
          uri: lb://catalog-service-docker
          predicates:
            - Path=/api/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalog-service-docker
                fallbackuri: forward:/catalogServiceFallBack

        - id: product-service-docker
          uri: lb://product-service-docker
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-service-docker
                fallbackuri: forward:/productServiceFallBack

        - id: swagger-service-docker
          uri: lb://swagger-service-docker
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service-docker
                fallbackuri: forward:/categoryServiceFallBack

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-clustered
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka, http://${eureka.instance.hostname}:8762/eureka, http://${eureka.instance.hostname}:8763/eureka


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
